<?php

namespace Database\Seeders;

use App\Models\Task;
use Illuminate\Database\Seeder;

class TaskSeeder extends Seeder
{
    public function run(): void
    {
        $tasks = [
            [
                'title' => 'Anmeldung (City Registration)',
                'description' => 'Register your address at the Bürgeramt within 14 days of moving in. This is required for almost everything else.',
                'situation' => ['non_eu_employee', 'eu_employee', 'student', 'freelancer', 'family_reunification', 'digital_nomad', 'other'],
                'phase' => 'first_weeks',
                'deadline_type' => 'days_since_arrival',
                'deadline_days' => 14,
                'urgency' => 'critical',
                'documents_required' => ['Passport', 'Rental contract (Wohnungsgeberbestätigung)', 'Anmeldeformular'],
                'links' => ['https://www.stadt-koeln.de/service/produkt/anmeldung-einer-wohnung-3'],
            ],
            [
                'title' => 'Health Insurance Registration',
                'description' => 'Register with a public or private health insurance provider. Required before you can work or study.',
                'situation' => ['non_eu_employee', 'eu_employee', 'student', 'freelancer', 'family_reunification', 'digital_nomad', 'other'],
                'phase' => 'first_weeks',
                'deadline_type' => 'days_since_arrival',
                'deadline_days' => 30,
                'urgency' => 'high',
                'documents_required' => ['Passport', 'Employment contract or university enrollment'],
                'links' => [],
            ],
            [
                'title' => 'Tax ID (Steuer-ID)',
                'description' => 'Your tax ID is automatically sent by post after Anmeldung. If it doesn\'t arrive within 4 weeks, contact the Finanzamt.',
                'situation' => ['non_eu_employee', 'eu_employee', 'student', 'freelancer', 'family_reunification', 'digital_nomad', 'other'],
                'phase' => 'first_month',
                'deadline_type' => 'days_since_arrival',
                'deadline_days' => 30,
                'urgency' => 'high',
                'documents_required' => ['Anmeldung confirmation'],
                'links' => [],
            ],
            [
                'title' => 'Ausländerbehörde Appointment',
                'description' => 'Book your appointment at the Foreigners\' Office for your residence permit.',
                'situation' => ['non_eu_employee', 'student', 'freelancer', 'family_reunification', 'digital_nomad'],
                'phase' => 'first_weeks',
                'deadline_type' => 'days_since_arrival',
                'deadline_days' => 30,
                'urgency' => 'critical',
                'documents_required' => ['Passport', 'Biometric photos', 'Anmeldung confirmation', 'Health insurance proof', 'Employment contract'],
                'links' => [],
            ],
            [
                'title' => 'Blue Card Application',
                'description' => 'Apply for the EU Blue Card at the Ausländerbehörde if you meet the salary threshold.',
                'situation' => ['non_eu_employee'],
                'phase' => 'first_month',
                'deadline_type' => 'days_since_arrival',
                'deadline_days' => 90,
                'urgency' => 'critical',
                'documents_required' => ['Passport', 'University degree (recognised)', 'Employment contract', 'Anmeldung', 'Health insurance'],
                'links' => [],
            ],
            [
                'title' => 'Bank Account',
                'description' => 'Open a German bank account. Needed for salary, rent, and all direct debits.',
                'situation' => ['non_eu_employee', 'eu_employee', 'student', 'freelancer', 'family_reunification', 'digital_nomad', 'other'],
                'phase' => 'first_month',
                'deadline_type' => 'days_since_arrival',
                'deadline_days' => 60,
                'urgency' => 'medium',
                'documents_required' => ['Passport', 'Anmeldung confirmation'],
                'links' => [],
            ],
            [
                'title' => 'SCHUFA Registration',
                'description' => 'Get your SCHUFA credit record started. Landlords and phone providers check this.',
                'situation' => ['non_eu_employee', 'eu_employee', 'student', 'freelancer', 'family_reunification', 'digital_nomad', 'other'],
                'phase' => 'settling',
                'deadline_type' => 'days_since_arrival',
                'deadline_days' => 90,
                'urgency' => 'low',
                'documents_required' => [],
                'links' => [],
            ],
            [
                'title' => 'Library Card',
                'description' => 'Get a Cologne city library card. Free access to books, WiFi, and study spaces.',
                'situation' => ['non_eu_employee', 'eu_employee', 'student', 'freelancer', 'family_reunification', 'digital_nomad', 'other'],
                'phase' => 'settling',
                'deadline_type' => 'none',
                'deadline_days' => null,
                'urgency' => 'low',
                'documents_required' => ['ID or passport', 'Anmeldung confirmation'],
                'links' => ['https://www.stadt-koeln.de/leben-in-koeln/stadtbibliothek/'],
            ],
            [
                'title' => 'EU Citizen Registration',
                'description' => 'Register as an EU citizen at the Bürgeramt. Simpler than non-EU registration.',
                'situation' => ['eu_employee'],
                'phase' => 'first_month',
                'deadline_type' => 'days_since_arrival',
                'deadline_days' => 90,
                'urgency' => 'medium',
                'documents_required' => ['Passport or national ID', 'Anmeldung confirmation', 'Employment contract or proof of income'],
                'links' => [],
            ],
            [
                'title' => 'Blocked Account (Sperrkonto)',
                'description' => 'Set up a blocked account with the required amount to prove financial means for your student visa.',
                'situation' => ['student'],
                'phase' => 'first_weeks',
                'deadline_type' => 'days_since_arrival',
                'deadline_days' => 14,
                'urgency' => 'critical',
                'documents_required' => ['Passport', 'University admission letter'],
                'links' => [],
            ],
            [
                'title' => 'Student Visa',
                'description' => 'Apply for or extend your student residence permit at the Ausländerbehörde.',
                'situation' => ['student'],
                'phase' => 'first_weeks',
                'deadline_type' => 'days_since_arrival',
                'deadline_days' => 14,
                'urgency' => 'critical',
                'documents_required' => ['Passport', 'University enrollment', 'Blocked account proof', 'Health insurance', 'Biometric photos'],
                'links' => [],
            ],
            [
                'title' => 'Enrollment Certificate',
                'description' => 'Get your enrollment certificate (Immatrikulationsbescheinigung) from your university.',
                'situation' => ['student'],
                'phase' => 'first_weeks',
                'deadline_type' => 'days_since_arrival',
                'deadline_days' => 14,
                'urgency' => 'high',
                'documents_required' => [],
                'links' => [],
            ],
            [
                'title' => 'Finanzamt Registration',
                'description' => 'Register your freelance activity with the local tax office (Finanzamt) using the Fragebogen zur steuerlichen Erfassung.',
                'situation' => ['freelancer'],
                'phase' => 'first_month',
                'deadline_type' => 'days_since_arrival',
                'deadline_days' => 30,
                'urgency' => 'high',
                'documents_required' => ['Tax ID', 'Passport', 'Anmeldung confirmation'],
                'links' => [],
            ],
            [
                'title' => 'Trade License (Gewerbeanmeldung)',
                'description' => 'If your work is classified as Gewerbe (trade), register at the Gewerbeamt. Freiberufler skip this.',
                'situation' => ['freelancer'],
                'phase' => 'first_month',
                'deadline_type' => 'days_since_arrival',
                'deadline_days' => 30,
                'urgency' => 'high',
                'documents_required' => ['Passport', 'Anmeldung confirmation', 'Residence permit'],
                'links' => [],
            ],
        ];

        foreach ($tasks as $task) {
            Task::create($task);
        }
    }
}
