<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gtfs-rt-tripupdate.proto

namespace App\Proto\TransitRealtime\TripUpdate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>transit_realtime.TripUpdate.StopTimeUpdate</code>
 */
class StopTimeUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 stop_sequence = 1;</code>
     */
    protected $stop_sequence = 0;
    /**
     * Generated from protobuf field <code>.transit_realtime.TripUpdate.StopTimeEvent arrival = 2;</code>
     */
    protected $arrival = null;
    /**
     * Generated from protobuf field <code>.transit_realtime.TripUpdate.StopTimeEvent departure = 3;</code>
     */
    protected $departure = null;
    /**
     * Generated from protobuf field <code>string stop_id = 4;</code>
     */
    protected $stop_id = '';
    /**
     * Generated from protobuf field <code>.transit_realtime.TripUpdate.StopTimeUpdate.ScheduleRelationship schedule_relationship = 5;</code>
     */
    protected $schedule_relationship = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $stop_sequence
     *     @type \App\Proto\TransitRealtime\TripUpdate\StopTimeEvent $arrival
     *     @type \App\Proto\TransitRealtime\TripUpdate\StopTimeEvent $departure
     *     @type string $stop_id
     *     @type int $schedule_relationship
     * }
     */
    public function __construct($data = NULL) {
        \App\Proto\GPBMetadata\GtfsRtTripupdate::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 stop_sequence = 1;</code>
     * @return int
     */
    public function getStopSequence()
    {
        return $this->stop_sequence;
    }

    /**
     * Generated from protobuf field <code>uint32 stop_sequence = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setStopSequence($var)
    {
        GPBUtil::checkUint32($var);
        $this->stop_sequence = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.TripUpdate.StopTimeEvent arrival = 2;</code>
     * @return \App\Proto\TransitRealtime\TripUpdate\StopTimeEvent|null
     */
    public function getArrival()
    {
        return $this->arrival;
    }

    public function hasArrival()
    {
        return isset($this->arrival);
    }

    public function clearArrival()
    {
        unset($this->arrival);
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.TripUpdate.StopTimeEvent arrival = 2;</code>
     * @param \App\Proto\TransitRealtime\TripUpdate\StopTimeEvent $var
     * @return $this
     */
    public function setArrival($var)
    {
        GPBUtil::checkMessage($var, \App\Proto\TransitRealtime\TripUpdate\StopTimeEvent::class);
        $this->arrival = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.TripUpdate.StopTimeEvent departure = 3;</code>
     * @return \App\Proto\TransitRealtime\TripUpdate\StopTimeEvent|null
     */
    public function getDeparture()
    {
        return $this->departure;
    }

    public function hasDeparture()
    {
        return isset($this->departure);
    }

    public function clearDeparture()
    {
        unset($this->departure);
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.TripUpdate.StopTimeEvent departure = 3;</code>
     * @param \App\Proto\TransitRealtime\TripUpdate\StopTimeEvent $var
     * @return $this
     */
    public function setDeparture($var)
    {
        GPBUtil::checkMessage($var, \App\Proto\TransitRealtime\TripUpdate\StopTimeEvent::class);
        $this->departure = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string stop_id = 4;</code>
     * @return string
     */
    public function getStopId()
    {
        return $this->stop_id;
    }

    /**
     * Generated from protobuf field <code>string stop_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setStopId($var)
    {
        GPBUtil::checkString($var, True);
        $this->stop_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.TripUpdate.StopTimeUpdate.ScheduleRelationship schedule_relationship = 5;</code>
     * @return int
     */
    public function getScheduleRelationship()
    {
        return $this->schedule_relationship;
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.TripUpdate.StopTimeUpdate.ScheduleRelationship schedule_relationship = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setScheduleRelationship($var)
    {
        GPBUtil::checkEnum($var, \App\Proto\TransitRealtime\TripUpdate\StopTimeUpdate\ScheduleRelationship::class);
        $this->schedule_relationship = $var;

        return $this;
    }

}

