<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gtfs-rt-tripupdate.proto

namespace App\Proto\TransitRealtime\TripDescriptor;

use UnexpectedValueException;

/**
 * Protobuf type <code>transit_realtime.TripDescriptor.ScheduleRelationship</code>
 */
class ScheduleRelationship
{
    /**
     * Generated from protobuf enum <code>SCHEDULED = 0;</code>
     */
    const SCHEDULED = 0;
    /**
     * Generated from protobuf enum <code>ADDED = 1;</code>
     */
    const ADDED = 1;
    /**
     * Generated from protobuf enum <code>UNSCHEDULED = 2;</code>
     */
    const UNSCHEDULED = 2;
    /**
     * Generated from protobuf enum <code>CANCELED = 3;</code>
     */
    const CANCELED = 3;
    /**
     * Generated from protobuf enum <code>REPLACEMENT = 5;</code>
     */
    const REPLACEMENT = 5;
    /**
     * Generated from protobuf enum <code>DUPLICATED = 6;</code>
     */
    const DUPLICATED = 6;
    /**
     * Generated from protobuf enum <code>DELETED = 7;</code>
     */
    const DELETED = 7;

    private static $valueToName = [
        self::SCHEDULED => 'SCHEDULED',
        self::ADDED => 'ADDED',
        self::UNSCHEDULED => 'UNSCHEDULED',
        self::CANCELED => 'CANCELED',
        self::REPLACEMENT => 'REPLACEMENT',
        self::DUPLICATED => 'DUPLICATED',
        self::DELETED => 'DELETED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

