<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gtfs-rt-tripupdate.proto

namespace App\Proto\TransitRealtime\FeedHeader;

use UnexpectedValueException;

/**
 * Protobuf type <code>transit_realtime.FeedHeader.Incrementality</code>
 */
class Incrementality
{
    /**
     * Generated from protobuf enum <code>FULL_DATASET = 0;</code>
     */
    const FULL_DATASET = 0;
    /**
     * Generated from protobuf enum <code>DIFFERENTIAL = 1;</code>
     */
    const DIFFERENTIAL = 1;

    private static $valueToName = [
        self::FULL_DATASET => 'FULL_DATASET',
        self::DIFFERENTIAL => 'DIFFERENTIAL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

