; Production PHP overrides
opcache.enable=1
opcache.memory_consumption=256
opcache.interned_strings_buffer=64
opcache.max_accelerated_files=30000
opcache.validate_timestamps=0

upload_max_filesize=20M
post_max_size=20M
memory_limit=256M
max_execution_time=60

expose_php=Off
