"""Explicit physical destination types; no unknown/vacant shop fallback."""

OSM_TYPES = {'amenity': {'pharmacy': 'pharmacy',
             'doctors': 'doctor',
             'dentist': 'dentist',
             'clinic': 'clinic',
             'hospital': 'hospital',
             'veterinary': 'veterinary',
             'bank': 'bank',
             'post_office': 'post_office',
             'community_centre': 'community_centre',
             'place_of_worship': 'place_of_worship',
             'marketplace': 'market',
             'theatre': 'theatre',
             'cinema': 'cinema',
             'arts_centre': 'arts_centre',
             'car_rental': 'car_rental',
             'pub': 'bar',
             'ice_cream': 'ice_cream',
             'language_school': 'language_school',
             'music_school': 'music_school'},
 'shop': {'supermarket': 'supermarket',
          'convenience': 'convenience',
          'kiosk': 'kiosk',
          'clothes': 'clothes',
          'shoes': 'shoes',
          'jewelry': 'jewelry',
          'department_store': 'department_store',
          'mall': 'shopping_centre',
          'variety_store': 'general_store',
          'bicycle': 'bicycle_shop',
          'sports': 'sports_shop',
          'outdoor': 'sports_shop',
          'books': 'bookshop',
          'stationery': 'stationery',
          'electronics': 'electronics',
          'mobile_phone': 'phone_shop',
          'computer': 'computer_shop',
          'furniture': 'furniture',
          'interior_decoration': 'homeware',
          'kitchen': 'homeware',
          'bed': 'homeware',
          'household_linen': 'homeware',
          'lighting': 'homeware',
          'carpet': 'homeware',
          'fabric': 'homeware',
          'bathroom_furnishing': 'homeware',
          'doityourself': 'hardware',
          'hardware': 'hardware',
          'paint': 'hardware',
          'garden_centre': 'garden_centre',
          'florist': 'florist',
          'pet': 'pet_shop',
          'toys': 'toy_shop',
          'games': 'toy_shop',
          'gift': 'gift_shop',
          'art': 'art_shop',
          'antiques': 'antiques',
          'second_hand': 'second_hand',
          'music': 'music_shop',
          'musical_instrument': 'music_shop',
          'beverages': 'drinks_shop',
          'alcohol': 'drinks_shop',
          'wine': 'drinks_shop',
          'coffee': 'coffee_tea_shop',
          'tea': 'coffee_tea_shop',
          'butcher': 'butcher',
          'greengrocer': 'greengrocer',
          'deli': 'delicatessen',
          'seafood': 'seafood_shop',
          'confectionery': 'confectionery',
          'pastry': 'bakery',
          'car': 'car_dealer',
          'car_parts': 'auto_parts',
          'motorcycle': 'motorcycle_shop',
          'hairdresser': 'hairdresser',
          'barber': 'hairdresser',
          'beauty': 'beauty',
          'cosmetics': 'beauty',
          'chemist': 'drugstore',
          'optician': 'optician',
          'hearing_aids': 'hearing_aids',
          'medical_supply': 'medical_supply',
          'laundry': 'laundry',
          'dry_cleaning': 'dry_cleaning',
          'tailor': 'tailor',
          'shoe_repair': 'shoe_repair',
          'car_repair': 'car_repair',
          'travel_agency': 'travel_agency',
          'ticket': 'ticket_shop',
          'massage': 'massage',
          'tattoo': 'tattoo',
          'copyshop': 'copy_shop',
          'pet_grooming': 'pet_grooming',
          'locksmith': 'locksmith',
          'bags': 'clothes',
          'fashion_accessories': 'clothes',
          'watches': 'jewelry',
          'camera': 'electronics',
          'photo': 'electronics',
          'video': 'electronics',
          'hifi': 'electronics',
          'electrical': 'electronics',
          'appliance': 'electronics',
          'sewing': 'homeware'},
 'leisure': {'fitness_centre': 'fitness_centre',
             'dance': 'dance_studio',
             'escape_game': 'escape_room'},
 'tourism': {'hotel': 'hotel',
             'hostel': 'hostel',
             'guest_house': 'guest_house',
             'motel': 'motel',
             'camp_site': 'campsite'}}

CATEGORY_LABELS = {'supermarket': 'Supermarket',
 'convenience': 'Convenience shop',
 'kiosk': 'Kiosk',
 'clothes': 'Clothes shop',
 'shoes': 'Shoe shop',
 'jewelry': 'Jewellery shop',
 'department_store': 'Department store',
 'shopping_centre': 'Shopping centre',
 'general_store': 'General shop',
 'bicycle_shop': 'Bicycle shop',
 'sports_shop': 'Sports shop',
 'bookshop': 'Bookshop',
 'stationery': 'Stationery shop',
 'electronics': 'Electronics shop',
 'phone_shop': 'Phone shop',
 'computer_shop': 'Computer shop',
 'furniture': 'Furniture shop',
 'homeware': 'Homeware shop',
 'hardware': 'Hardware shop',
 'garden_centre': 'Garden centre',
 'florist': 'Florist',
 'pet_shop': 'Pet shop',
 'toy_shop': 'Toy shop',
 'gift_shop': 'Gift shop',
 'art_shop': 'Art shop',
 'antiques': 'Antiques shop',
 'second_hand': 'Second-hand shop',
 'music_shop': 'Music shop',
 'drinks_shop': 'Drinks shop',
 'coffee_tea_shop': 'Coffee and tea shop',
 'butcher': 'Butcher',
 'greengrocer': 'Greengrocer',
 'delicatessen': 'Delicatessen',
 'seafood_shop': 'Seafood shop',
 'confectionery': 'Confectionery shop',
 'car_dealer': 'Car dealership',
 'auto_parts': 'Car parts shop',
 'motorcycle_shop': 'Motorcycle shop',
 'hairdresser': 'Hairdresser',
 'beauty': 'Beauty salon',
 'laundry': 'Laundry',
 'dry_cleaning': 'Dry cleaner',
 'tailor': 'Tailor',
 'shoe_repair': 'Shoe repair',
 'car_repair': 'Car repair',
 'travel_agency': 'Travel agency',
 'ticket_shop': 'Ticket office',
 'massage': 'Massage studio',
 'tattoo': 'Tattoo studio',
 'copy_shop': 'Copy shop',
 'pet_grooming': 'Pet grooming',
 'locksmith': 'Locksmith',
 'bank': 'Bank',
 'post_office': 'Post office',
 'car_rental': 'Car rental',
 'pharmacy': 'Pharmacy',
 'drugstore': 'Drugstore',
 'doctor': 'Doctor',
 'dentist': 'Dentist',
 'optician': 'Optician',
 'hearing_aids': 'Hearing aid specialist',
 'medical_supply': 'Medical supplies',
 'clinic': 'Clinic',
 'hospital': 'Hospital',
 'veterinary': 'Veterinary clinic',
 'community_centre': 'Community centre',
 'place_of_worship': 'Place of worship',
 'language_school': 'Language school',
 'music_school': 'Music school',
 'hotel': 'Hotel',
 'hostel': 'Hostel',
 'guest_house': 'Guest house',
 'motel': 'Motel',
 'campsite': 'Campsite',
 'fitness_centre': 'Gym',
 'dance_studio': 'Dance studio',
 'theatre': 'Theatre',
 'cinema': 'Cinema',
 'arts_centre': 'Arts centre',
 'escape_room': 'Escape room',
 'ice_cream': 'Ice cream shop',
 'market': 'Market'}
