<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gtfs-rt-tripupdate.proto

namespace App\Proto\TransitRealtime\TripUpdate\StopTimeUpdate;

use UnexpectedValueException;

/**
 * Protobuf type <code>transit_realtime.TripUpdate.StopTimeUpdate.ScheduleRelationship</code>
 */
class ScheduleRelationship
{
    /**
     * Generated from protobuf enum <code>SCHEDULED = 0;</code>
     */
    const SCHEDULED = 0;
    /**
     * Generated from protobuf enum <code>SKIPPED = 1;</code>
     */
    const SKIPPED = 1;
    /**
     * Generated from protobuf enum <code>NO_DATA = 2;</code>
     */
    const NO_DATA = 2;
    /**
     * Generated from protobuf enum <code>UNSCHEDULED = 3;</code>
     */
    const UNSCHEDULED = 3;

    private static $valueToName = [
        self::SCHEDULED => 'SCHEDULED',
        self::SKIPPED => 'SKIPPED',
        self::NO_DATA => 'NO_DATA',
        self::UNSCHEDULED => 'UNSCHEDULED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

