<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gtfs-rt-tripupdate.proto

namespace App\Proto\TransitRealtime;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>transit_realtime.FeedMessage</code>
 */
class FeedMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.transit_realtime.FeedHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * Generated from protobuf field <code>repeated .transit_realtime.FeedEntity entity = 2;</code>
     */
    private $entity;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Proto\TransitRealtime\FeedHeader $header
     *     @type \App\Proto\TransitRealtime\FeedEntity[] $entity
     * }
     */
    public function __construct($data = NULL) {
        \App\Proto\GPBMetadata\GtfsRtTripupdate::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.FeedHeader header = 1;</code>
     * @return \App\Proto\TransitRealtime\FeedHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.FeedHeader header = 1;</code>
     * @param \App\Proto\TransitRealtime\FeedHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \App\Proto\TransitRealtime\FeedHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .transit_realtime.FeedEntity entity = 2;</code>
     * @return RepeatedField<\App\Proto\TransitRealtime\FeedEntity>
     */
    public function getEntity()
    {
        return $this->entity;
    }

    /**
     * Generated from protobuf field <code>repeated .transit_realtime.FeedEntity entity = 2;</code>
     * @param \App\Proto\TransitRealtime\FeedEntity[] $var
     * @return $this
     */
    public function setEntity($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Proto\TransitRealtime\FeedEntity::class);
        $this->entity = $arr;

        return $this;
    }

}

