<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gtfs-rt-tripupdate.proto

namespace App\Proto\TransitRealtime;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>transit_realtime.FeedEntity</code>
 */
class FeedEntity extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>bool is_deleted = 2;</code>
     */
    protected $is_deleted = false;
    /**
     * Generated from protobuf field <code>.transit_realtime.TripUpdate trip_update = 3;</code>
     */
    protected $trip_update = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type bool $is_deleted
     *     @type \App\Proto\TransitRealtime\TripUpdate $trip_update
     * }
     */
    public function __construct($data = NULL) {
        \App\Proto\GPBMetadata\GtfsRtTripupdate::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_deleted = 2;</code>
     * @return bool
     */
    public function getIsDeleted()
    {
        return $this->is_deleted;
    }

    /**
     * Generated from protobuf field <code>bool is_deleted = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDeleted($var)
    {
        GPBUtil::checkBool($var);
        $this->is_deleted = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.TripUpdate trip_update = 3;</code>
     * @return \App\Proto\TransitRealtime\TripUpdate|null
     */
    public function getTripUpdate()
    {
        return $this->trip_update;
    }

    public function hasTripUpdate()
    {
        return isset($this->trip_update);
    }

    public function clearTripUpdate()
    {
        unset($this->trip_update);
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.TripUpdate trip_update = 3;</code>
     * @param \App\Proto\TransitRealtime\TripUpdate $var
     * @return $this
     */
    public function setTripUpdate($var)
    {
        GPBUtil::checkMessage($var, \App\Proto\TransitRealtime\TripUpdate::class);
        $this->trip_update = $var;

        return $this;
    }

}

