<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gtfs-rt-tripupdate.proto

namespace App\Proto\TransitRealtime;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>transit_realtime.FeedHeader</code>
 */
class FeedHeader extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string gtfs_realtime_version = 1;</code>
     */
    protected $gtfs_realtime_version = '';
    /**
     * Generated from protobuf field <code>.transit_realtime.FeedHeader.Incrementality incrementality = 2;</code>
     */
    protected $incrementality = 0;
    /**
     * Generated from protobuf field <code>uint64 timestamp = 3;</code>
     */
    protected $timestamp = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $gtfs_realtime_version
     *     @type int $incrementality
     *     @type int|string $timestamp
     * }
     */
    public function __construct($data = NULL) {
        \App\Proto\GPBMetadata\GtfsRtTripupdate::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string gtfs_realtime_version = 1;</code>
     * @return string
     */
    public function getGtfsRealtimeVersion()
    {
        return $this->gtfs_realtime_version;
    }

    /**
     * Generated from protobuf field <code>string gtfs_realtime_version = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setGtfsRealtimeVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->gtfs_realtime_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.FeedHeader.Incrementality incrementality = 2;</code>
     * @return int
     */
    public function getIncrementality()
    {
        return $this->incrementality;
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.FeedHeader.Incrementality incrementality = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setIncrementality($var)
    {
        GPBUtil::checkEnum($var, \App\Proto\TransitRealtime\FeedHeader\Incrementality::class);
        $this->incrementality = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 timestamp = 3;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>uint64 timestamp = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->timestamp = $var;

        return $this;
    }

}

