<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gtfs-rt-tripupdate.proto

namespace App\Proto\TransitRealtime;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>transit_realtime.TripUpdate</code>
 */
class TripUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.transit_realtime.TripDescriptor trip = 1;</code>
     */
    protected $trip = null;
    /**
     * Generated from protobuf field <code>repeated .transit_realtime.TripUpdate.StopTimeUpdate stop_time_update = 2;</code>
     */
    private $stop_time_update;
    /**
     * Generated from protobuf field <code>uint64 timestamp = 4;</code>
     */
    protected $timestamp = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Proto\TransitRealtime\TripDescriptor $trip
     *     @type \App\Proto\TransitRealtime\TripUpdate\StopTimeUpdate[] $stop_time_update
     *     @type int|string $timestamp
     * }
     */
    public function __construct($data = NULL) {
        \App\Proto\GPBMetadata\GtfsRtTripupdate::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.TripDescriptor trip = 1;</code>
     * @return \App\Proto\TransitRealtime\TripDescriptor|null
     */
    public function getTrip()
    {
        return $this->trip;
    }

    public function hasTrip()
    {
        return isset($this->trip);
    }

    public function clearTrip()
    {
        unset($this->trip);
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.TripDescriptor trip = 1;</code>
     * @param \App\Proto\TransitRealtime\TripDescriptor $var
     * @return $this
     */
    public function setTrip($var)
    {
        GPBUtil::checkMessage($var, \App\Proto\TransitRealtime\TripDescriptor::class);
        $this->trip = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .transit_realtime.TripUpdate.StopTimeUpdate stop_time_update = 2;</code>
     * @return RepeatedField<\App\Proto\TransitRealtime\TripUpdate\StopTimeUpdate>
     */
    public function getStopTimeUpdate()
    {
        return $this->stop_time_update;
    }

    /**
     * Generated from protobuf field <code>repeated .transit_realtime.TripUpdate.StopTimeUpdate stop_time_update = 2;</code>
     * @param \App\Proto\TransitRealtime\TripUpdate\StopTimeUpdate[] $var
     * @return $this
     */
    public function setStopTimeUpdate($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Proto\TransitRealtime\TripUpdate\StopTimeUpdate::class);
        $this->stop_time_update = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 timestamp = 4;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>uint64 timestamp = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->timestamp = $var;

        return $this;
    }

}

