<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gtfs-rt-tripupdate.proto

namespace App\Proto\TransitRealtime;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>transit_realtime.TripDescriptor</code>
 */
class TripDescriptor extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string trip_id = 1;</code>
     */
    protected $trip_id = '';
    /**
     * Generated from protobuf field <code>string start_time = 2;</code>
     */
    protected $start_time = '';
    /**
     * Generated from protobuf field <code>string start_date = 3;</code>
     */
    protected $start_date = '';
    /**
     * Generated from protobuf field <code>.transit_realtime.TripDescriptor.ScheduleRelationship schedule_relationship = 4;</code>
     */
    protected $schedule_relationship = 0;
    /**
     * Generated from protobuf field <code>string route_id = 5;</code>
     */
    protected $route_id = '';
    /**
     * Generated from protobuf field <code>uint32 direction_id = 6;</code>
     */
    protected $direction_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $trip_id
     *     @type string $start_time
     *     @type string $start_date
     *     @type int $schedule_relationship
     *     @type string $route_id
     *     @type int $direction_id
     * }
     */
    public function __construct($data = NULL) {
        \App\Proto\GPBMetadata\GtfsRtTripupdate::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string trip_id = 1;</code>
     * @return string
     */
    public function getTripId()
    {
        return $this->trip_id;
    }

    /**
     * Generated from protobuf field <code>string trip_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTripId($var)
    {
        GPBUtil::checkString($var, True);
        $this->trip_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string start_time = 2;</code>
     * @return string
     */
    public function getStartTime()
    {
        return $this->start_time;
    }

    /**
     * Generated from protobuf field <code>string start_time = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->start_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string start_date = 3;</code>
     * @return string
     */
    public function getStartDate()
    {
        return $this->start_date;
    }

    /**
     * Generated from protobuf field <code>string start_date = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStartDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->start_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.TripDescriptor.ScheduleRelationship schedule_relationship = 4;</code>
     * @return int
     */
    public function getScheduleRelationship()
    {
        return $this->schedule_relationship;
    }

    /**
     * Generated from protobuf field <code>.transit_realtime.TripDescriptor.ScheduleRelationship schedule_relationship = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setScheduleRelationship($var)
    {
        GPBUtil::checkEnum($var, \App\Proto\TransitRealtime\TripDescriptor\ScheduleRelationship::class);
        $this->schedule_relationship = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string route_id = 5;</code>
     * @return string
     */
    public function getRouteId()
    {
        return $this->route_id;
    }

    /**
     * Generated from protobuf field <code>string route_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setRouteId($var)
    {
        GPBUtil::checkString($var, True);
        $this->route_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 direction_id = 6;</code>
     * @return int
     */
    public function getDirectionId()
    {
        return $this->direction_id;
    }

    /**
     * Generated from protobuf field <code>uint32 direction_id = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setDirectionId($var)
    {
        GPBUtil::checkUint32($var);
        $this->direction_id = $var;

        return $this;
    }

}

